### ISSUE TITLE
Fabric 1.19.2 support

### ISSUE THREAD

**Issue by ENC4YP7ED** [HyeroDrimm/HorseArmorStandMod#1]
look at title

**Comment by HyeroDrimm** [comment]
What about it

**Comment by HyeroDrimm** [comment]
Srry not completed

**Comment by HyeroDrimm** [comment]
Ok, so I don't know how I misunderstood this then, but sorry. I won't be adding support for 1.19, cos library I use doesn't have features I need in those versions. Again, sorry for miscommunication on my part, and thank you for sending the issue. Thread closed.
