### ISSUE TITLE
Entity constantly displays the name "Horse Armor Stand"

### ISSUE THREAD

**Issue by Jvkeh** [HyeroDrimm/HorseArmorStandMod#2]

**Comment by Jvkeh** [comment]
Is there any way to disable this? I looked through the source code, and couldn't figure out a way I was meant to be able to disable it. There is no config. It's annoying to see this name through all my walls from max render distance away.

**Comment by HyeroDrimm** [comment]
Could you send screenshots?

**Comment by Jvkeh** [comment]
![2024-04-12_14 40 03](https://github.com/HyeroDrimm/HorseArmorStandMod/assets/34066256/5df3f33c-5ba6-4fa6-8be5-f403512cdd9e)
![2024-04-12_14 40 09](https://github.com/HyeroDrimm/HorseArmorStandMod/assets/34066256/39b81260-5b25-4c36-804e-dcf75843436c)

As you can see, the name is above the armor stand, and is visible through blocks, just like a player nametag

**Comment by HyeroDrimm** [comment]
ok, thanks for screens, can you post also your mod list and verison?

**Comment by PieceMaker085** [comment]
Any chance to address this bug @HyeroDrimm ?
I installed a completely new Fabric 1.20.4 instance of Minecraft without any mods except this one. The name label above the horse armor stand entity still shows so I don't think this is due to some other mod or shader.

**Comment by LeGerbi** [comment]
I got the same issue, you can rename it in an anvil to something shorter, however you cannot totally leave the name blank. (I'm on version 1.20.1)

**Comment by HyeroDrimm** [comment]
Bug was fixed, new version is available on Modrinth. Thank you for your input.

**Comment by PieceMaker085** [comment]
Thank you very much!

**Comment by PieceMaker085** [comment]
@HyeroDrimm , sorry for bothering again, but will there be a 1.20.4 compatible version of this fix?

**Comment by HyeroDrimm** [comment]
I wasn't planning making it, but if you need it I will provide. Will inform you when its done.

**Comment by HyeroDrimm** [comment]
@PieceMaker085 Done, check out [Modrinth](https://modrinth.com/mod/horse-armor-stand/version/iIWrUwdE)

**Comment by PieceMaker085** [comment]
@HyeroDrimm, thank you again for fixing this. Works like a charm.
