### ISSUE TITLE
[Request] Different poses, armor stand riders

### ISSUE THREAD

**Issue by chimericdream** [HyeroDrimm/HorseArmorStandMod#5]
I'm so glad I came across this mod! Have you thought about implementing different poses, like trotting, rearing up, etc? What about right-clicking the horse stand with a regular armor stand to give it a rider?

**Comment by HyeroDrimm** [comment]
Hi, thank you for kind comment and suggestion <3. I was thinking about adding different poses, and now that I see there is interest in those, maybe I will add them, but no promises ;). 

About the rider, it would be a lot of work to implement that feature correctly, so I won't be doing those. But I think you can add a rider yourself with existing tools, like pistoning horse armor into a block and dropping an armor stand on it. Good luck!

**Comment by chimericdream** [comment]
Glad to hear you like the idea of different poses. The bit about riders makes sense. I look forward to seeing what you come up with!

I totally understand the "no promises" bit, by the way. It's easy for stuff like this to get out of hand.

**Comment by HyeroDrimm** [comment]
I messed around a bit and here is what I made:

![2024-09-22_12 13 44](https://github.com/user-attachments/assets/0eb66cc1-fe0e-405a-a4c6-62c328147d56)

You need to have setup like this:

![2024-09-22_12 17 22](https://github.com/user-attachments/assets/2b29c4c4-3729-4395-a152-030bd2774a60)

Then push half slab two times under horse armor stand and drop normal armor stand. Very vanilla XD
