### ISSUE TITLE
Resourcepack - Compatibility Fix with Fresh Animations Extension

### ISSUE THREAD

**Issue by PieceMaker085** [HyeroDrimm/HorseArmorStandMod#6]
Just want to give a heads up that I made a fix resourcepack that changes the model used by Armor Stand Mod to the horse model used by Fresh Animations Extension.

![fa_hasm_comp_header](https://github.com/user-attachments/assets/d978ae91-2b5c-4b4b-8c3d-4dbacecd330e)

[https://modrinth.com/resourcepack/fresh-animations-fix-for-horse-armor-stand-mod](https://modrinth.com/resourcepack/fresh-animations-fix-for-horse-armor-stand-mod)

@HyeroDrimm , if you want you can link to this fix on the Armor Stand Mod page since this fix has been requested by many players.
All credits have been given to respective original content creators.

**Comment by HyeroDrimm** [comment]
Yea sure, thanks for fixing this issue <3
