### ISSUE TITLE
Crash minutes after placing horse armor stand

### ISSUE THREAD

**Issue by Russeki** [HyeroDrimm/HorseArmorStandMod#8]
**After placing the armor stand in a build that I was working on, my game suddenly crashed 1-2 minutes after.

Idk much about these things but here is the log: https://mclo.gs/jL2LLu0

**Comment by HyeroDrimm** [comment]
I think I found the issue, but just to check it, are you playing on some modpack? Can you somehow send me your MC instance?

**Comment by HyeroDrimm** [comment]
There is new version to try, please download it

**Comment by Russeki** [comment]
> There is new version to try, please download it

Ok, I'll try it now
